spring:
   datasource:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/dw_501?useUnicode=true&charaterEncoding=utf-8&serverTimezone=UTC
      username: root
      password: tkddnjs0823
   # hibernate.ddl.auto option : 
   # create: 기존테이블 삭제 후 다시 생성 (DROP + CREATE)
   # create-drop: create와 같으나 종료시점에 테이블 DROP
   # update: 변경분만 반영(운영DB에서는 사용하면 안됨)
   # validate: 엔티티와 테이블이 정상 매핑되었는지만 확인
   # none: 사용하지 않음
   jpa:
      database: mysql
      generate-ddl: true
      hibernate.ddl.auto: update
      show-sql: true